use retail_capstone_db;
select * from customers;
select customer_name,city,membership_type from customers;
select * from products order by price desc;
select * from customers where city='Hyderabad';
select * from customers where membership_type='Gold';
select * from products where price between 500 and 5000;
select * from products where category in('Electronics','Fashion');
select * from orders where order_date>'2026-01-01';
select * from payments where payment_mode='UPI';
select * from deliveries where delivery_status='Pending';
select count(*) as total_customers from customers;
select count(*) as total_orders from orders;
select count(*) as total_products from products;
select sum(amount) as total_revenue from payments where payment_status='Success';
select round(avg(amount),2) as avg_payment_amount from payments;
select max(amount) as highest_payment from payments;
select min(amount) as lowest_payment from payments;
select city,count(*) as customer_count from customers group by city order by customer_count desc;
select category,count(*) as product_count from products group by category order by product_count desc;
select order_status,count(*) as order_count from orders group by order_status order by order_count desc;
select c.customer_name,o.order_id,o.order_date from customers c join orders o on c.customer_id=o.customer_id;
select oi.order_id,p.product_name,oi.quantity,p.price from order_items oi join products p on oi.product_id=p.product_id;
select c.customer_name,p.product_name,oi.quantity,o.order_date from customers c join orders o on c.customer_id=o.customer_id join order_items oi on o.order_id=oi.order_id join products p on oi.product_id=p.product_id;
select o.order_id,py.payment_mode,py.payment_status,py.amount from orders o join payments py on o.order_id=py.order_id;
select o.order_id,d.delivery_partner,d.delivery_status from orders o join deliveries d on o.order_id=d.order_id;
select c.customer_name,c.city,o.order_id,o.order_date,p.product_name,p.category,oi.quantity,p.price,py.payment_status,d.delivery_status from customers c join orders o on c.customer_id=o.customer_id join order_items oi on o.order_id=oi.order_id join products p on oi.product_id=p.product_id join payments py on o.order_id=py.order_id join deliveries d on o.order_id=d.order_id order by o.order_date,o.order_id;
select c.city,sum(py.amount) as total_revenue from customers c join orders o on c.customer_id=o.customer_id join payments py on o.order_id=py.order_id where py.payment_status='Success' group by c.city order by total_revenue desc;
select c.customer_name,sum(py.amount) as total_spent from customers c join orders o on c.customer_id=o.customer_id join payments py on o.order_id=py.order_id where py.payment_status='Success' group by c.customer_id,c.customer_name order by total_spent desc;
select p.product_name,sum(oi.quantity) as total_quantity_sold from products p join order_items oi on p.product_id=oi.product_id group by p.product_id,p.product_name order by total_quantity_sold desc;
select p.category,sum(oi.quantity*p.price) as category_revenue from products p join order_items oi on p.product_id=oi.product_id join orders o on oi.order_id=o.order_id join payments py on o.order_id=py.order_id where py.payment_status='Success' group by p.category order by category_revenue desc;
select c.customer_name,count(o.order_id) as order_count from customers c join orders o on c.customer_id=o.customer_id group by c.customer_id,c.customer_name order by order_count desc;
select c.customer_name,count(o.order_id) as order_count from customers c join orders o on c.customer_id=o.customer_id group by c.customer_id,c.customer_name having count(o.order_id)>1;
select p.category,sum(oi.quantity*p.price) as category_revenue from products p join order_items oi on p.product_id=oi.product_id group by p.category having sum(oi.quantity*p.price)>10000 order by category_revenue desc;
select city,count(*) as customer_count from customers group by city having count(*)>2;
select p.product_name,sum(oi.quantity) as total_sold from products p join order_items oi on p.product_id=oi.product_id group by p.product_id,p.product_name having sum(oi.quantity)>3;
select * from customers where customer_id in(select distinct customer_id from orders);
select * from customers where customer_id not in(select distinct customer_id from orders);
select * from products where product_id not in(select distinct product_id from order_items);
select * from orders where order_id in(select order_id from payments where amount>(select avg(amount) from payments));
select * from customers where customer_id=(select o.customer_id from orders o join payments py on o.order_id=py.order_id where py.amount=(select max(amount) from payments) limit 1);
select * from products where price>(select avg(price) from products);
select distinct c.* from customers c where c.customer_id in(select o.customer_id from orders o join order_items oi on o.order_id=oi.order_id join products p on oi.product_id=p.product_id where p.category='Electronics');
select * from orders where order_id in(select order_id from payments where payment_status='Success');
select * from orders where order_id not in(select order_id from deliveries where delivery_status='Delivered');
select c.customer_name,sum(py.amount) as total_spent from customers c join orders o on c.customer_id=o.customer_id join payments py on o.order_id=py.order_id where py.payment_status='Success' group by c.customer_id,c.customer_name having sum(py.amount)>(select avg(customer_total) from(select customer_id,sum(py2.amount) as customer_total from orders o2 join payments py2 on o2.order_id=py2.order_id where py2.payment_status='Success' group by o2.customer_id) as avg_sub);
select * from orders where order_id not in(select distinct order_id from payments);
select * from orders where order_id not in(select distinct order_id from deliveries);
select * from payments where amount is null or amount=0;
select o.order_id,o.order_status,py.payment_status,py.amount from orders o join payments py on o.order_id=py.order_id where o.order_status='Cancelled' and py.payment_status='Success';
select o.order_id,o.order_status,py.payment_status,py.amount from orders o join payments py on o.order_id=py.order_id where o.order_status='Delivered' and py.payment_status='Failed';
select * from order_items where product_id not in(select product_id from products);
select * from orders where customer_id not in(select customer_id from customers);